"""Create papers, authors, topics, and association tables

Revision ID: 698eb7bcff4d
Revises: 
Create Date: 2026-08-16 12:50:59.073165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '698eb7bcff4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_author_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_openalex_author_id'), 'authors', ['openalex_author_id'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openalex_work_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_openalex_work_id'), 'papers', ['openalex_work_id'], unique=True)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'author_id')
    )
    op.create_table('paper_topics',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'topic_id')
    )
    # ### end Alembic commands ###

    # --- hand-added: not picked up by autogenerate ---

    # Full-text search index on title + abstract (GET /papers keyword search).
    # A functional GIN index rather than a stored tsvector column, so it's always
    # in sync with the data automatically -- no trigger to maintain.
    op.execute("""
        CREATE INDEX ix_papers_fulltext
        ON papers
        USING GIN (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(abstract, '')))
    """)

    # Approximate nearest-neighbor index for embedding similarity search (Part 3 AI feature).
    # ivfflat needs a rough `lists` value; 100 is a reasonable default for a corpus in the
    # low thousands. cosine distance ops since sentence-transformers embeddings are compared
    # by cosine similarity.
    op.execute("""
        CREATE INDEX ix_papers_embedding_cosine
        ON papers
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # hand-added indexes, dropped first since they depend on the papers table
    op.execute("DROP INDEX IF EXISTS ix_papers_embedding_cosine")
    op.execute("DROP INDEX IF EXISTS ix_papers_fulltext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_topics')
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_openalex_work_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_authors_openalex_author_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
